services:
  - type: web
    name: real-insights-api
    env: node
    plan: starter
    buildCommand: npm install -g pnpm@9.6.0 && pnpm install --frozen-lockfile && pnpm build:api
    startCommand: cd apps/api && pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-insights-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
    healthCheckPath: /
    
databases:
  - name: real-insights-db
    databaseName: real_insights
    plan: starter 