services:
  - type: web
    name: real-insights-api
    env: node
    plan: standard
    region: oregon
    buildCommand: |
      npm install -g pnpm@9.6.0 && 
      pnpm install --frozen-lockfile && 
      echo "Generating Prisma client globally..." && 
      pnpm db:generate && 
      echo "Building db package..." && 
      pnpm --filter @repo/db build && 
      echo "Generating Prisma client for API..." && 
      cd apps/api && pnpm exec prisma generate --schema=../../packages/db/schema.prisma && cd ../.. &&
      echo "Building API..." && 
      pnpm --filter api build && 
      echo "Checking generated files..." && 
      ls -la packages/db/dist/ && 
      ls -la apps/api/dist/ &&
      echo "Checking node_modules/.prisma..." &&
      ls -la node_modules/.prisma/ || echo "No .prisma directory found"
    startCommand: cd apps/api && pnpm start:prod
    
    autoDeploy: true
    numInstances: 3
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-insights-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: DATABASE_POOL_SIZE
        value: "20"
      - key: DATABASE_CONNECTION_LIMIT
        value: "100"
    
    healthCheckPath: /api/v1/health
    
    disk:
      name: real-insights-api-disk
      size: 20GB
      
databases:
  - name: real-insights-db
    databaseName: real_insights
    plan: standard
    region: oregon
    
    ipAllowList: []
    
# Optional: Redis for caching (recommended for 10K users)
# - type: redis
#   name: real-insights-redis
#   plan: starter
#   region: oregon 