name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Vercel
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Vercel secrets are configured
        id: check-vercel
        run: |
          if [[ -n "${{ secrets.VERCEL_TOKEN }}" && -n "${{ secrets.VERCEL_ORG_ID }}" && -n "${{ secrets.VERCEL_PROJECT_ID }}" ]]; then
            echo "configured=true" >> $GITHUB_OUTPUT
          else
            echo "configured=false" >> $GITHUB_OUTPUT
            echo "⚠️  Vercel secrets not configured. Skipping deployment."
          fi

      - name: Install pnpm
        if: steps.check-vercel.outputs.configured == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 9.6.0

      - name: Setup Node.js
        if: steps.check-vercel.outputs.configured == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Deploy to Vercel
        if: steps.check-vercel.outputs.configured == 'true'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install -g pnpm@9.6.0
          npm install -g vercel@latest
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --yes

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-frontend]
    if: always()
    
    steps:
      - name: Deployment Status
        run: |
          echo "Frontend deployment: ${{ needs.deploy-frontend.result }}" 